### ISSUE TITLE
Multiple issues on the code examples present in the README file.

### ISSUE THREAD

**Issue by dxflores** [goodboy/tractor#108]
Note: almost all examples require __name__ == '__main__': ... to even be run. 

##############################################################################
Example 5: (Async generators)

```$: python t5.py ```

```python
No actor could be found @ 127.0.0.1:1616
I can see these little future bubble things
already have channel(s) for ('donny', '0888e2f3-4cf6-48c3-be8d-8b4e5d96ec66'):[<Channel fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 1616), raddr=('127.0.0.1', 51820)>]?
I can see these little future bubble things
I can see these little future bubble things # This line prints ~200 times
...
I can see these little future bubble things
Cancelling stream dad8746d-4c44-4683-a0ba-7c94b9dcb85f to ('donny', '0888e2f3-4cf6-48c3-be8d-8b4e5d96ec66')
Stream connection ('127.0.0.1', 51820) broke
May have failed to cancel remote task dad8746d-4c44-4683-a0ba-7c94b9dcb85f for ('donny', '0888e2f3-4cf6-48c3-be8d-8b4e5d96ec66')
Nursery for ('arbiter', '2ed87e2b-1a5c-4438-94bb-e9877347a940') errored with Cancelled, 
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_trionics.py", line 223, in open_nursery
    yield anursery
  File "t5.py", line 22, in main
    async for letter in await portal.run(__name__, 'stream_forever'):
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_abc.py", line 623, in __anext__
    return await self.receive()
  File "/home/x/tractor/tractor/_portal.py", line 67, in receive
    msg = await self._rx_chan.receive()
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_channel.py", line 290, in receive
    return await trio.hazmat.wait_task_rescheduled(abort_fn)
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_traps.py", line 165, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/home/x/tractor/T/lib/python3.8/site-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 1072, in raise_cancel
    raise Cancelled._create()
trio.Cancelled: Cancelled
This portal is already closed can't cancel
Nursery cancelling due to Cancelled(), Cancelled()
This portal is already closed can't cancel
```
##############################################################################

Example: 6 (full streaming service)

`$: python t6.py`

```python
ttr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__
, 
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_trionics.py", line 223, in open_nursery
    yield anursery
  File "/home/x/tractor/t6.py", line 57, in aggregate
    print("FINISHED ITERATING in aggregator")
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/x/tractor/t6.py", line 32, in push_to_chan
    async for value in await portal.run(__name__, 'stream_data', seed=seed):
  File "/home/x/tractor/tractor/_portal.py", line 186, in run
    *(await self._submit(ns, func, kwargs))
  File "/home/x/tractor/tractor/_portal.py", line 167, in _submit
    raise unpack_error(first_msg, self.channel)
tractor._exceptions.RemoteActorError: ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__

Sending actor cancel request to ('streamer_2', '315f73a5-d53f-419d-ab2e-c502881ca048') on <Channel fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 36013), raddr=('127.0.0.1', 34064)>
Sending actor cancel request to ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33') on <Channel fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 36013), raddr=('127.0.0.1', 34060)>
Task <bound method Actor.cancel of <tractor._actor.Actor object at 0x7f18250872b0>> was likely cancelled before it was started
Task <bound method Actor.cancel of <tractor._actor.Actor object at 0x7f3d999e72b0>> was likely cancelled before it was started
May have failed to cancel ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
May have failed to cancel ('streamer_2', '315f73a5-d53f-419d-ab2e-c502881ca048')
Nursery cancelling due to ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__

Actor errored:
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 93, in _invoke
    async for item in agen:
  File "/home/x/tractor/t6.py", line 57, in aggregate
    print("FINISHED ITERATING in aggregator")
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/x/tractor/t6.py", line 32, in push_to_chan
    async for value in await portal.run(__name__, 'stream_data', seed=seed):
  File "/home/x/tractor/tractor/_portal.py", line 186, in run
    *(await self._submit(ns, func, kwargs))
  File "/home/x/tractor/tractor/_portal.py", line 167, in _submit
    raise unpack_error(first_msg, self.channel)
tractor._exceptions.RemoteActorError: ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__

Nursery for ('arbiter', '19959b2f-8838-4400-a52c-533e38b84119') errored with ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 93, in _invoke
    async for item in agen:
  File "/home/x/tractor/t6.py", line 57, in aggregate
    print("FINISHED ITERATING in aggregator")
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/x/tractor/t6.py", line 32, in push_to_chan
    async for value in await portal.run(__name__, 'stream_data', seed=seed):
  File "/home/x/tractor/tractor/_portal.py", line 186, in run
    *(await self._submit(ns, func, kwargs))
  File "/home/x/tractor/tractor/_portal.py", line 167, in _submit
    raise unpack_error(first_msg, self.channel)
tractor._exceptions.RemoteActorError: ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__

, 
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_portal.py", line 68, in receive
    return msg['yield']
KeyError: 'yield'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_trionics.py", line 223, in open_nursery
    yield anursery
  File "t6.py", line 80, in main
    async for value in await portal.result():
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_abc.py", line 623, in __anext__
    return await self.receive()
  File "/home/x/tractor/tractor/_portal.py", line 82, in receive
    raise unpack_error(msg, self._portal.channel)
tractor._exceptions.RemoteActorError: ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 93, in _invoke
    async for item in agen:
  File "/home/x/tractor/t6.py", line 57, in aggregate
    print("FINISHED ITERATING in aggregator")
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/x/tractor/t6.py", line 32, in push_to_chan
    async for value in await portal.run(__name__, 'stream_data', seed=seed):
  File "/home/x/tractor/tractor/_portal.py", line 186, in run
    *(await self._submit(ns, func, kwargs))
  File "/home/x/tractor/tractor/_portal.py", line 167, in _submit
    raise unpack_error(first_msg, self.channel)
tractor._exceptions.RemoteActorError: ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__


Cancelling all streams with ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Cancelling stream 74ea1f75-4b6c-4831-8167-30c13585ead0 to ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Cancelling all streams with ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Cancelling stream 74ea1f75-4b6c-4831-8167-30c13585ead0 to ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
74ea1f75-4b6c-4831-8167-30c13585ead0 has already completed/terminated?
74ea1f75-4b6c-4831-8167-30c13585ead0 has already completed/terminated?
Sending actor cancel request to ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764') on <Channel fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 1616), raddr=('127.0.0.1', 51856)>
Sending actor cancel request to ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764') on <Channel fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 1616), raddr=('127.0.0.1', 51856)>
Task <bound method Actor.cancel of <tractor._actor.Actor object at 0x7f4578ed6250>> was likely cancelled before it was started
already have channel(s) for ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764'):[<Channel fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 1616), raddr=('127.0.0.1', 51856)>]?
Stream connection ('127.0.0.1', 51856) broke
Cancelling existing result waiter task for ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
May have failed to cancel ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
May have failed to cancel ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Nursery cancelling due to ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 93, in _invoke
    async for item in agen:
  File "/home/x/tractor/t6.py", line 57, in aggregate
    print("FINISHED ITERATING in aggregator")
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/x/tractor/t6.py", line 32, in push_to_chan
    async for value in await portal.run(__name__, 'stream_data', seed=seed):
  File "/home/x/tractor/tractor/_portal.py", line 186, in run
    *(await self._submit(ns, func, kwargs))
  File "/home/x/tractor/tractor/_portal.py", line 167, in _submit
    raise unpack_error(first_msg, self.channel)
tractor._exceptions.RemoteActorError: ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__


Traceback (most recent call last):
  File "/home/x/tractor/tractor/_portal.py", line 68, in receive
    return msg['yield']
KeyError: 'yield'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t6.py", line 91, in <module>
    final_stream = tractor.run(main, arbiter_addr=('127.0.0.1', 1616))
  File "/home/x/tractor/tractor/__init__.py", line 114, in run
    return trio.run(_main, async_fn, args, kwargs, arbiter_addr, name)
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/x/tractor/tractor/__init__.py", line 91, in _main
    return await _start_actor(
  File "/home/x/tractor/tractor/_actor.py", line 945, in _start_actor
    result = await main()
  File "t6.py", line 80, in main
    async for value in await portal.result():
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_abc.py", line 623, in __anext__
    return await self.receive()
  File "/home/x/tractor/tractor/_portal.py", line 82, in receive
    raise unpack_error(msg, self._portal.channel)
tractor._exceptions.RemoteActorError: ('aggregator', '6b6836d7-bd58-40de-b257-abc830c38764')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 93, in _invoke
    async for item in agen:
  File "/home/x/tractor/t6.py", line 57, in aggregate
    print("FINISHED ITERATING in aggregator")
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 730, in __aexit__
    raise combined_error_from_nursery
  File "/home/x/tractor/t6.py", line 32, in push_to_chan
    async for value in await portal.run(__name__, 'stream_data', seed=seed):
  File "/home/x/tractor/tractor/_portal.py", line 186, in run
    *(await self._submit(ns, func, kwargs))
  File "/home/x/tractor/tractor/_portal.py", line 167, in _submit
    raise unpack_error(first_msg, self.channel)
tractor._exceptions.RemoteActorError: ('streamer_1', '70d0d4a4-1881-4365-8321-530a9acc2e33')
Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 287, in _get_rpc_func
    return getattr(self._mods[ns], funcname)
KeyError: '__main__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/tractor/tractor/_actor.py", line 491, in _process_messages
    func = self._get_rpc_func(ns, funcname)
  File "/home/x/tractor/tractor/_actor.py", line 289, in _get_rpc_func
    raise ModuleNotExposed(*err.args)
tractor._exceptions.ModuleNotExposed: __main__
```

##############################################################################

Example: 7 (Service discovery)

`$: python t7.py`

```python
No actor could be found @ 127.0.0.1:1616
Traceback (most recent call last):
  File "t7.py", line 15, in <module>
    tractor.run(main, 'some_actor_name')
  File "/home/x/tractor/tractor/__init__.py", line 114, in run
    return trio.run(_main, async_fn, args, kwargs, arbiter_addr, name)
  File "/home/x/tractor/T/lib/python3.8/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/home/x/tractor/tractor/__init__.py", line 91, in _main
    return await _start_actor(
  File "/home/x/tractor/tractor/_actor.py", line 945, in _start_actor
    result = await main()
  File "t7.py", line 6, in main
    async with tractor.get_arbiter() as portal:
  File "/home/x/tractor/T/lib/python3.8/site-packages/async_generator/_util.py", line 106, in helper
    return _AsyncGeneratorContextManager(func, args, kwds)
  File "/home/x/tractor/T/lib/python3.8/site-packages/async_generator/_util.py", line 28, in __init__
    self._agen = func(*args, **kwds).__aiter__()
TypeError: get_arbiter() missing 2 required positional arguments: 'host' and 'port'
```
##############################################################################

**Comment by goodboy** [comment]
@dxflores so you're `t5.py` is actually fine. If you echo `$ echo $?` you'll get `0`. It's just logging that spitting "errors" on the console.

Still looking at the others which do appear to have problems..

**Comment by goodboy** [comment]
Hmm so you `t6.py` is actually a regression introduced from #93 to do with fixing up the `__main__` module in sub-processes.  I have to dig into this one a little to figure out what I've done wrong.

**Comment by goodboy** [comment]
Heh and yeah `t7.py` was just plain not a real example that had every been tested lol!

I've changed it now in the script that'll be part of the testing in #102 but it probably won't show up in the docs until we do #99. Might as well get this all done in one shot!
